version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins-server-container
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agent
      - "2222:22"     # SSH access (optional)
    volumes:
      - jenkins_home:/var/jenkins_home

  spring:
    build:
      context: .
    container_name: project-server-container
    ports:
      - "8000:8000"   # Spring Boot 서버 포트
    depends_on:
      - db

  db:
    build:
      context: ./db
    container_name: postgres-server-container
    environment:
      POSTGRES_USER: project_1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_1_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  jenkins_home:
  postgres_data:
