spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:6543/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate  # 운영 환경에서는 validate 또는 none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:init-db/initDB-PG.sql  # 경로 확인 필요