FROM postgres:latest

# 환경 변수 설정
ENV POSTGRES_USER=project_1
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=project_1_db

# 사용자 계정 및 권한 부여를 위한 SQL 스크립트 추가
COPY init-db.sql /docker-entrypoint-initdb.d/

# 방화벽 설정 (외부에서 접근 가능)
EXPOSE 5432
