-- T_USER 테이블 생성
CREATE TABLE IF NOT EXISTS T_USER (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 자동 증가 컬럼 설정 (IDENTITY)
    USERNAME VARCHAR(50),
    PASSWORD VARCHAR(100)
);

-- 데이터 삽입
INSERT INTO T_USER (USERNAME, PASSWORD) VALUES ('admin', 'a');